### ISSUE TITLE
broken in Atom 1.1+

### ISSUE THREAD

**Issue by geddski** [nukkio/duplicate-and-comment#2]
![image](https://cloud.githubusercontent.com/assets/515722/11138295/afee8fac-897d-11e5-96c9-9c73a5872d90.png)

**Comment by geddski** [comment]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.2.0
**System**: Mac OS X 10.11.1
**Thrown From**: [duplicate-and-comment](https://github.com/nukkio/duplicate-and-comment) package, v0.2.0

### Stack Trace

Failed to activate the duplicate-and-comment package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (/Users/dave/.atom/packages/duplicate-and-comment/lib/duplicate-and-comment.coffee:4:32)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:170:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:512:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:495:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:490:19)
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "git-history",
      "whitespace",
      "open-on-github",
      "file-types",
      "git-blame-plus"
    ],
    "destroyEmptyPanes": true,
    "themes": [
      "one-dark-ui",
      "seti-syntax"
    ],
    "packagesWithKeymapsDisabled": [
      "emmet"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
autocomplete-paths, v1.0.2
color-picker, v2.0.13
docblockr, v0.7.3
duplicate-and-comment, v0.2.0
emmet, v2.3.14
file-icons, v1.6.11
highlight-selected, v0.10.1
pain-split, v1.4.0
pigments, v0.18.1
pretty-json, v0.4.1
project-manager, v2.6.5
react, v0.12.10
seti-syntax, v0.4.1

# Dev
No dev packages
```

**Comment by geddski** [comment]
@nukkio still broken
